### PR TITLE
Update SPI slot definition

### PR DESCRIPTION
**Pull request by tokurz**
It shows me when I install the edge gadget invalid plugs and slots for SPI I adjust the names, l hope its working now.

### CODE REVIEW

**Review by zyga — COMMENTED** [review]
Maybe we want spidev0_0 or spidevA_0 or something similar.

**Comment by zyga** [comment]
Thank you for updating this PR. Can you check that the new names build fine and install on a device correctly?

**Comment by tokurz** [comment]
sure, when I can install the new version from snapstore? Today? Tomorrow?

**Comment by zyga** [comment]
You can build the snap locally and build an image with it.

**Comment by tokurz** [comment]
I have tested it and now the ports shows fine in the snap interfaces part

**Review by zyga — APPROVED** [review]
LGTM, CCing @mvo5 for awareness

**Comment by cdamman** [comment]
@ogra1 could you please review this so that it could be merged ?
I have one project needing the SPI devices...

**Comment by tokurz** [comment]
@ogra1  please check if you use my last commit, I have saw that there is an error when I install the gadget-snap i have modified it.

**Review by ogra1 — CHANGES_REQUESTED** [review]
can you drop the fixrtc from cmdline,txt ? this is redundant, uboot.env.in sets it in snappy_cmdline. otherwise it looks good

**Comment by tokurz** [comment]
@ogra1  its dropped

**Review by ogra1 — APPROVED** [review]

**Comment by ogra1** [comment]
another nitpick, the turning on of audio and forcing on of the rtc module are technically not related, can you at least mention them in the PR summary somehow ?

**Pull request closed without merging**
